#!/bin/bash
# Fix GitHub Authentication

echo ""
echo "=========================================="
echo "  GitHub Authentication Fix"
echo "=========================================="
echo ""

# Remove existing remote
echo "Removing existing remote..."
git remote remove origin 2>/dev/null || true

echo ""
echo "GitHub Authentication Options:"
echo ""
echo "Option 1: Personal Access Token (Recommended)"
echo "==========================================="
echo ""
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token' -> 'Generate new token (classic)'"
echo "3. Give it a name: 'k3s-homelab'"
echo "4. Select scopes: 'repo' (full control of private repositories)"
echo "5. Click 'Generate token'"
echo "6. COPY THE TOKEN (you'll only see it once!)"
echo ""
echo "Then use this command to push:"
echo ""
echo "  git remote add origin https://YOUR_TOKEN@github.com/ahmed86-star/k3s-homelab.git"
echo "  git push -u origin main"
echo ""
echo "Replace YOUR_TOKEN with your actual token"
echo ""
echo "=========================================="
echo ""
echo "Option 2: SSH (Alternative)"
echo "==========================================="
echo ""
echo "1. Generate SSH key:"
echo "   ssh-keygen -t ed25519 -C 'your_email@example.com'"
echo ""
echo "2. Copy public key:"
echo "   cat ~/.ssh/id_ed25519.pub"
echo ""
echo "3. Add to GitHub: https://github.com/settings/keys"
echo ""
echo "4. Use SSH URL:"
echo "   git remote add origin git@github.com:ahmed86-star/k3s-homelab.git"
echo "   git push -u origin main"
echo ""
echo "=========================================="
echo ""

read -p "Press Enter to continue..."

